### ISSUE TITLE
Conventions

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#230]
So after walking through all of our components with @przspa we wrote down the conventions that should be used to standarize them. We tried to find a common patterns easily appliable to every component and scenario. 

The purpose of those conventions is to have easy to use and learn API that works similar for similar use cases (so it's predictable).

1. [ ] Use Passing Listeners pattern and bind `v-on="$listeners"` on components root to hoist events (example SfArrow).  https://github.com/DivanteLtd/storefront-ui/issues/253
2. [ ] Use scoped slots for markup customization and put template inside them`<slot :prop="prop">//template</slot>` instead of wrapping slot into a markup with `v-for` or `click` event. Just give people needed data properties and methods and let them handle whole section markup by themselves. https://github.com/DivanteLtd/storefront-ui/issues/254
3. [ ] Use v-bind in slot scope `<slot v-bind="{foo, bar}"></slot>` instead of passing scope properties one by one (example SfBreadcrumbs).  
4. [ ] Use semantic HTML representation of the component that is not tied to CSS (avoid unnecessary wrappers, use correct HTML tags). It's a must-have to enable storefront-ui themes to feature in a near future. https://github.com/DivanteLtd/storefront-ui/issues/255
5. [ ] If there is more than 1 slot make all of them named ones. The only exception is when default slot is a default way of configuring the component (for example SfButton) https://github.com/DivanteLtd/storefront-ui/issues/256
6. [ ] Use always PascalCase for components in templates (https://vuejs.org/v2/style-guide/#Component-name-casing-in-templates-strongly-recommended) to easily distinguish them from HTML tags.  
7. [x] Provide default value of a prop instead of marking it as required.
8. [x] Internal components (for example SfAccordionItem that belongs to SfAccordion) shouldn't have separate SCSS files. Since internal component is just a part of it's parent it's styling should be treated as a whole.
9. [ ] BEM class names should be similar as scoped slot names that are replacing those BEM Blocks..  
10. [ ] When we use nested components inside other component their props should be passed to parent component with the same name + component name (for example when we have `SfPrice` (that has `regular`, `special`, `old` props) inside `SfProductCard`  we add `regularPrice`, `specialPrice` etc.

## What's next

I'm leaving this document for a few days to discuss all of the conventions. feel free to challange them or propose more!

Once we agree on those conventions every one will become an issue. I hope i can count ion your help with closing them!

**Comment by leomp12** [comment]
Sounds good :)

**Comment by leomp12** [comment]
We may also write conventions for prop names and object modeling.
We're usually adopting simple prop and slot names, in almost all cases with one word only.
When having more complex props (nested objects or array of objects), we may try to follow same conventions for nested property names, and we must define string case for property names, wdyt about it, pascal case or snake case?
```js
myProp.nested_prop = 'any'
```
```js
myProp.nestedProp = 'any'
```

**Comment by filrak** [comment]
@leomp12 good point and I agree with camel case ;)

The thing that I want to heavily discuss is point 2. For example. If we take a look at this PR:
https://github.com/DivanteLtd/storefront-ui/pull/222

according to new convention we should have:
```html
<div class="sf-carousel__controls">
      <!--@slot slot for icon moving to the previous item -->
      <slot name="prev" v-bind="{ go }">
        <div @click="go('prev')">
          <SfArrow
            class="sf-arrow--long"
            aria-label="previous"/>
        </div>
      </slot>
      <!--@slot slot for icon moving to the next item -->
      <slot name="next" v-bind="{ go }">
        <div @click="go('next')">
          <SfArrow
            class="sf-arrow--long sf-arrow--right"
            aria-label="next"/>
        </div>
      </slot>
  </div>
```
instead of
```html
<div class="sf-carousel__controls">
    <div @click="go('prev')">
      <!--@slot slot for icon moving to the previous item -->
      <slot name="prev">
        <SfArrow
          class="sf-arrow--long"
          aria-label="previous"/>
      </slot>
    </div>
    <div @click="go('next')">
      <!--@slot slot for icon moving to the next item -->
      <slot name="next">
        <SfArrow
          class="sf-arrow--long sf-arrow--right"
          aria-label="next"/>
      </slot>
    </div>
  </div>
```
While this approach is generally great for complicated use cases and limitless customization (since user only gets a scoped slot) it adds extra steps for simle ones (like the above where you need to explicitly include click handler. In other cases you might need to do v-for by yourself etc). 

I'm curious about your opinion here @leomp12 @mayashavin

**Comment by leomp12** [comment]
I don't think it would be a problem in this example, but as I commented on discord, I also don't think this approach is the best _always_, but almost always.
Anyway I agree we may use it as convention always to be predictable :)

**Comment by runyasak** [comment]
> Use scoped slots for markup customization and put template inside them<slot :prop="prop">//template</slot> instead of wrapping slot into a markup with v-for or click event. 

I'm agree with this use case. I have wrapped slot with `v-for` then it would iterate to content of slot. It makes component hardly reusing. 😁
