### ISSUE TITLE
Beta release checklist

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#247]
Tasks that we need to finish before beta :

**Silent beta**
- [x] Global color modifiers https://github.com/DivanteLtd/storefront-ui/issues/209
- [x] Conventions https://github.com/DivanteLtd/storefront-ui/issues/230
- [x] SfTabs adjustment ( @Michal-Dziedzinski )
- [ ] Testing of all the components in SSR env like Nuxt
- [x] Adjustment of form elements to play together well ( @runyasak )
- [ ] SfAddToCart https://github.com/DivanteLtd/storefront-ui/issues/207 ( @mayashavin )
- [ ] Testing components "in action" -> examples
- [x] Mobile SfSelect https://github.com/DivanteLtd/storefront-ui/issues/251

**Public beta**
- Docs (I'm working on it)
- Testing components "in action" part 2 -> more examples
- New components: Footer, Header, SfAvatar + 2 more we are discussing with @przspa

**Comment by mayashavin** [comment]
SfAddToCart #207 
Need to define what is missing in Docs I think :)

**Comment by filrak** [comment]
Everything :)

**Comment by filrak** [comment]
But we should come up with agenda. I'll come up with something similar to what I did for Vue Storefront https://github.com/DivanteLtd/vue-storefront/issues/2495 but feel free to propose what should be there in this thread too ;)
